#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyCube;
    using NewLife;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_DateRange.cshtml")]
    public partial class _Views_Shared__DateRange_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__DateRange_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_DateRange.cshtml"
  
    var formatStr = (Model is String) ? Model : "yyyy-MM-dd";
    var p = ViewBag.Page as Pager;

            
            #line default
            #line hidden
WriteLiteral("\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n    <label");

WriteLiteral(" for=\"dtStart\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">时间：</label>\n    <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\n        <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-calendar\"");

WriteLiteral("></i></span>\n        <input");

WriteLiteral(" name=\"dtStart\"");

WriteLiteral(" id=\"dtStart\"");

WriteAttribute("value", Tuple.Create(" value=\"", 336), Tuple.Create("\"", 357)
            
            #line 9 "..\..\Views\Shared\_DateRange.cshtml"
, Tuple.Create(Tuple.Create("", 344), Tuple.Create<System.Object, System.Int32>(p["dtStart"]
            
            #line default
            #line hidden
, 344), false)
);

WriteAttribute("dateformat", Tuple.Create(" dateformat=\"", 358), Tuple.Create("\"", 381)
            
            #line 9 "..\..\Views\Shared\_DateRange.cshtml"
, Tuple.Create(Tuple.Create("", 371), Tuple.Create<System.Object, System.Int32>(formatStr
            
            #line default
            #line hidden
, 371), false)
);

WriteLiteral(" class=\"form-control form_datetime\"");

WriteLiteral(" />\n    </div>\n</div>\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n    <label");

WriteLiteral(" for=\"dtEnd\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">至</label>\n    <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\n        <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-calendar\"");

WriteLiteral("></i></span>\n        <input");

WriteLiteral(" name=\"dtEnd\"");

WriteLiteral(" id=\"dtEnd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 665), Tuple.Create("\"", 684)
            
            #line 16 "..\..\Views\Shared\_DateRange.cshtml"
, Tuple.Create(Tuple.Create("", 673), Tuple.Create<System.Object, System.Int32>(p["dtEnd"]
            
            #line default
            #line hidden
, 673), false)
);

WriteAttribute("dateformat", Tuple.Create(" dateformat=\"", 685), Tuple.Create("\"", 708)
            
            #line 16 "..\..\Views\Shared\_DateRange.cshtml"
, Tuple.Create(Tuple.Create("", 698), Tuple.Create<System.Object, System.Int32>(formatStr
            
            #line default
            #line hidden
, 698), false)
);

WriteLiteral(" class=\"form-control form_datetime\"");

WriteLiteral(" />\n    </div>\n</div>");

        }
    }
}
#pragma warning restore 1591
